[versions]
compose = "1.7.3"
kotlin = "2.1.20-RC2"

[libraries]

[plugins]
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
